# Generated by Django 3.1.3 on 2021-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='donations',
            name='order_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donations',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='donations',
            name='amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donations',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donations',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
